<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.2" />
    <ProjectReference Include="../OpenFlix.Identity/OpenFlix.Identity.csproj" />
    <ProjectReference Include="../OpenFlix.Catalog/OpenFlix.Catalog.csproj" />
    <ProjectReference Include="../OpenFlix.Subscriptions/OpenFlix.Subscriptions.csproj" />
    <ProjectReference Include="../OpenFlix.Gateway/OpenFlix.Gateway.csproj" />
  </ItemGroup>
</Project>
